### ISSUE TITLE
Update contribution/guidelines

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#110]
## ToDo

- [x] Fix links in README
- [x] Add link to `enV5-base-project` repo
- [x] Add install guide for MacOS
- [ ] add pre-commit  [Hiwi](https://github.com/orgs/es-ude/projects/5/views/1?filterQuery=assignee%3A%40me&pane=issue&itemId=37134521)
