### ISSUE TITLE
Concept for a File-System for the Flash-Storage

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#156]
Gather informations about a basic concept for a File-System for the Flash Storage to proper manage the occupied space from binary files.

## ToDo's

- [ ] Possible Data for the File-System (ID of Binfile, Sektor where the Binfile starts)?
- [ ] Name for the abstraction of a flash sector
- [ ] Possible Size reserved for File-System data

**Comment by DavidFederl** [comment]
Maybe a start point: [DOI 10.1109/ICEET53442.2021.9659672](https://doi.org/10.1109/ICEET53442.2021.9659672)

**Comment by DavidFederl** [comment]
Existing solutions always utilise some form of splitting data into chunks. This doesn't work for us, because the FPGA requires the config file to be one consecutive read from the flash!

**Comment by HerrCooker** [comment]
Result: 
- for now a basic Sector and fileID datastructure stored in the last sectors of the flash will suffice
- CFFS may be a good idea in the future
