### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#170]
Update the Documentation in a way, that new student workers/developers are able to understand the code base without much introduction.

---

## TODO
- [x] README
- [x] HAL Libraries
- [x] Flash Library
- [x] Sensor Libraries
- [x] RTOS library
- [x] Network Libraries
- [x] FPGA Libraries

**Comment by DavidFederl** [comment]
- [ ] Write a _SETUP_GUIDE.adoc_

---

## Setup Guide

Step By Step Guide how to setup every tool, regarding CLion as IDE.

**Comment by DavidFederl** [comment]
- [ ]  Convert Markdown based Documentation to [Asciidoc](https://docs.asciidoctor.org/asciidoc/latest/)

---

## Asciidoc

**Benefits:**
- Richer Ecosystem out of the box
    - External Sorce Code Includes
    - Improved Tables
    - Einfach zu erweitern
- Supported by GitHub/Gitlab/...
- Supported by IDEs (IDEA, CLion, PyCharm, ...)

**Comment by DavidFederl** [comment]
# Test

Added via GH CLI

@ME

**Comment by DavidFederl** [comment]
- [ ] [add link to landing page](https://github.com/orgs/es-ude/projects/5/views/1?pane=issue&itemId=38063247)

**Comment by DavidFederl** [comment]
- [ ] Add XVC-Pico to Vivado Debugger Guide

**Comment by DavidFederl** [comment]
Also see https://github.com/es-ude/elastic-ai.runtime.enV5/issues/171#issuecomment-1813112144
