### ISSUE TITLE
OTA update of RP2040 binary

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#215]
## Concept

1. Download Binary to program flash via HTTPGet
2. Validate downloaded program
3. Reboot to Execute new program

Based on: https://github.com/es-ude/elastic-ai.runtime.enV5/issues/100#issuecomment-2009156809

## ToDo

- [ ] Test the implementation provided by [rp2040 serial bootloader](https://github.com/usedbytes/rp2040-serial-bootloader)
- [ ] Modify the implementation, so that multiple executable can be stored at the same time
- [ ] Add update functionality via HTTPGet to the enV5 code base and test if it works
- [ ] Add additional security by validating new binary against Hash transmitted over secured channel

## Notes

- Multiple binaries at the same time: 
    - modification of the custom bootloader storage -> add additional information about which one should be executed
    - define two static start address for the different binaries to reduce complexity during build time
    - add handler to reload old binary if startup with new binary failed

**Comment by DerDavidos** [comment]
Used this implementatin instead: https://github.com/rhulme/pico-flashloader#using-in-your-own-project. Flashing over usb successful with example
