### ISSUE TITLE
Integrate BMI323 library

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#232]
Integrate the [BMI323 Library](https://github.com/boschsensortec/BMI323_SensorAPI) from Bosch into the sensor libraries.

This sensor will be connected utilizing the SPI Pins provided on the Wifi-Extension-Board.
-> SPI_1 with GPIO08-11

## TODO

- [x] Integrate Library
- [ ] Write Unit-Tests
- [x] Write Integration-Test
- [x] Validate Implementation with Hardware

**Comment by DavidFederl** [comment]
## Additional Tasks:

- [ ] Provide complete Facade with CException

> [!IMPORTANT] 
> **Unit-Tests** doesn't make much sense  here since the implementation is provided 'as is' by Bosch Sensotec!
